module Algorithms.README where
open import Algorithms.Bin
open import Algorithms.Equality
open import Algorithms.Miscellaneous
open import Algorithms.OrderedCollection.BinarySearchTree
open import Algorithms.OrderedCollection.Bounded
open import Algorithms.OrderedCollection.RedBlackTree
open import Algorithms.PriorityQueue.Bounded
open import Algorithms.PriorityQueue.LeftistHeap
open import Algorithms.StrictTotalOrder
open import Algorithms.TotalOrder
